"""Criação inicial do banco de dados

Revision ID: eafee0caa0c0
Revises: 
Create Date: 2025-08-03 17:03:37.676621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafee0caa0c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodo',
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=30), nullable=True),
    sa.Column('datainicial', sa.Date(), nullable=False),
    sa.Column('datafinal', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_periodo')
    )
    op.create_table('tipocalendario',
    sa.Column('id_tipo', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=4), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo')
    )
    op.create_table('calendario',
    sa.Column('id_calendario', sa.Integer(), nullable=False),
    sa.Column('id_tipo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('datainicio', sa.Date(), nullable=False),
    sa.Column('datafim', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo'], ['tipocalendario.id_tipo'], ),
    sa.PrimaryKeyConstraint('id_calendario')
    )
    op.create_table('categoriacalendario',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_calendario', sa.Integer(), nullable=False),
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('corassociada', sa.String(length=30), nullable=True),
    sa.Column('totaldias', sa.Integer(), nullable=True),
    sa.Column('diassemanasvalidos', sa.String(length=30), nullable=True),
    sa.Column('habilitacaocontagem', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_calendario'], ['calendario.id_calendario'], ),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodo.id_periodo'], ),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('eventos',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('datainicio', sa.Date(), nullable=False),
    sa.Column('datafim', sa.Date(), nullable=False),
    sa.Column('dia_todo', sa.Boolean(), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoriacalendario.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    op.drop_table('categoriacalendario')
    op.drop_table('calendario')
    op.drop_table('tipocalendario')
    op.drop_table('periodo')
    # ### end Alembic commands ###
